user  root;
worker_processes  1;

events {
}

http {
    client_max_body_size 200M;

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name appraiserspov.com www.appraiserspov.com;
        return 301 https://$host$request_uri;
    }

    # HTTPS Server Block
    server {
        listen 443 ssl;
        server_name appraiserspov.com;

        ssl_certificate /etc/letsencrypt/live/appraiserspov.com/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/appraiserspov.com/privkey.pem;

        # Proxy API requests to the backend container
        location /api/ {
            proxy_set_header Cookie $http_cookie;   # forward all cookies
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host              $host:$server_port;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
            proxy_connect_timeout 7200s;
            proxy_send_timeout 7200s;
            proxy_read_timeout 7200s;
        }

        # Proxy all other requests to the frontend container
        location / {
            proxy_pass http://frontend:3000/;
        }
    }
}
