user  root;
worker_processes  1;

events {
}

http {
    client_max_body_size 200M;

    # Redirect HTTP to HTTPS
    server {
        listen 80;
        server_name mytestapp.online www.mytestapp.online;
        return 301 https://$host$request_uri;
    }

    # HTTPS Server Block
    server {
        listen 443 ssl;
        server_name mytestapp.online;

        ssl_certificate /etc/letsencrypt/live/mytestapp.online/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/mytestapp.online/privkey.pem;

        # Proxy API requests to the backend container
        location /api/ {
            proxy_pass http://backend:8080/api/;
        }

        # Proxy all other requests to the frontend container
        location / {
            proxy_pass http://frontend:3000/;
        }
    }
}
