user  root;
worker_processes  1;

events {
}

http {
    client_max_body_size 200M;

    # The server will listen on port 80 inside the container.
    # We'll map host port -> container port in docker-compose.yml
    server {
        listen 80;
        server_name  localhost;  # or your server IP

        # Any request that starts with /api/ goes to backend container
        location /api/ {
            proxy_pass http://backend:8080/api/;
            # The trailing slash ensures the path matches /api/...
            # and proxies the remainder to the backend.
        }

        # All other requests go to the frontend container's port 3000
        location / {
            proxy_pass http://frontend:3000/;
        }
    }
}
