user  root;
worker_processes  1;

events {
}

http {
    client_max_body_size 200M;

    # The server will listen on port 80 inside the container.
    # We'll map host port -> container port in docker-compose.yml
    server {
        listen 80;
        server_name  3.144.93.8;  # or your server IP

        # Any request that starts with /api/ goes to backend container
        location /api/ {
            # proxy_pass http://backend:8000/;
            proxy_pass http://backend:8080/api/;
            proxy_set_header Host              $host:$server_port;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_redirect off;
            proxy_connect_timeout 7200s;
            proxy_send_timeout 7200s;
            proxy_read_timeout 7200s;
        }

        # All other requests go to the frontend container's port 3000
        location / {
            proxy_pass http://frontend:3000/;
        }
    }
}
