spring.profiles.active=${SPRING_PROFILES_ACTIVE}
server.port=${SERVER_PORT}
# Common JPA settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.show-sql=true
spring.jpa.hibernate.ddl-auto=none
# Liquibase configuration
spring.liquibase.change-log=classpath:liquibase/main-liquibase.xml
spring.liquibase.enabled=true
# MapServ Utah Gov
mapserv.utah.base-url=https://api.mapserv.utah.gov
mapserv.utah.apikey=${MAPSERV_UTAH_GOV_KEY}
# ArcGIS
arcgis.base-url=https://www.arcgis.com/sharing/rest
arcgis.username=MichaelNyman
arcgis.api.key=${ARCGIS_API_KEY}
# Google
google.oauth2.client-id=${GOOGLE_CLIENT_ID}
google.oauth2.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth2.redirect-uri=${APP_LINKS_BASE_URL}/api/google/oauth2/callback
google.oauth2.scopes=https://www.googleapis.com/auth/spreadsheets
google.oauth2.authorize-base-url=https://accounts.google.com/o/oauth2/v2/auth
google.oauth2.token-base-url=https://oauth2.googleapis.com/token
google.sheets.default.spreadsheet.url=https://docs.google.com/spreadsheets/d/
google.sheets.api.baseUrl=https://sheets.googleapis.com/v4/spreadsheets

#App Config
app.links.base-url=${APP_LINKS_BASE_URL}
app.links.layers=${app.links.base-url}/api/openApi/layers/
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.forward-headers-strategy=native
# ----------------------------------------------------------------
# JWT Settings
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
# OAuth2 client settings (Google)
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
# Adjust the base URL as needed if your app is at e.g. http://localhost:8080

# Wait 2 hours (7200 seconds) for the server to read the entire request
server.tomcat.connection-timeout=7200000
# to allow large request bodies.
server.tomcat.max-swallow-size=-1


