spring.datasource.url=${DATABASE_URL:jdbc:postgresql://database:5432/gis_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
# CORS
application.cors.allowed.origins=http://localhost:3000,https://localhost:3001,http://localhost:3001,http://localhost:80,http://localhost:81,http://localhost:8080,http://localhost
# FRONT-END
application.front-end.url=http://localhost:3001
#server.port=8443
#server.ssl.enabled=true
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=123456
#server.ssl.key-store-type=PKCS12

google.oauth2.client-id=${GOOGLE_CLIENT_ID}
google.oauth2.client-secret=${GOOGLE_CLIENT_SECRET}
google.oauth2.redirect-uri=${APP_LINKS_BASE_URL}/api/google/oauth2/callback
google.oauth2.scopes=https://www.googleapis.com/auth/spreadsheets
google.oauth2.authorize-base-url=https://accounts.google.com/o/oauth2/v2/auth
google.oauth2.token-base-url=https://oauth2.googleapis.com/token




