# CORS
application.cors.allowed.origins=http://nginx:80,https://nginx:443,http://18.207.125.37,http://18.207.125.37:80,https://18.207.125.37:443,https://mytestapp.online,http://3.144.93.8,https://3.144.93.8,http://appraiserspov.com,https://appraiserspov.com

# DB
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://database:5432/gis_db}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

# FRONT-END
application.front-end.url=${APP_LINKS_BASE_URL}
