server.ssl.enabled=true
server.ssl.key-store=keystore.jks
server.ssl.key-store-password=${KEY_STORE_PASSWORD}
server.ssl.key-alias=tomcat

application.cors.allowed.origins=http://localhost:80,http://localhost:443,http://localhost,http://nginx:80,http://18.207.125.37,http://18.207.125.37:80,http://18.207.125.37:443
