# CORS
application.cors.allowed.origins=http://nginx:80,https://nginx:443,http://18.207.125.37,http://18.207.125.37:80,https://18.207.125.37:443,https://mytestapp.online

# DB
spring.datasource.url=jdbc:h2:mem:real_estate_db;DB_CLOSE_DELAY=-1
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driverClassName=org.h2.Driver

# FRONT-END
application.front-end.url=https://mytestapp.online
